const vent = [
  {
    _id: "6415b0d1aef39ae82c93389d",
    userId: "6415a045d7154777b2bc3121",
    userPicturePath:
      "https://tse1.mm.bing.net/th/id/OIP.mHW53jey0964kxQqcgCj9gHaLH?pid=ImgDet&w=199&h=298&c=7&dpr=1.3",
    userName: "abel",
    ventMood: "tired",
    ventText:
      "😘First time doing this so bare with me ,This one is something that's been on my mind for a while..for anyone who has been exposed to qorn from a young age and who is addicted...how do y'all keep going in life through the guilt, depression,loss of self esteem etc...and anyone who's no longer addicted. How did you overcome the temptation?",
    tags: ["afraied"],
    feelingSame: 2,
    hug: 3,
    smile: 3,
    surprized: 7,
    createdAt: "2023-03-18T12:38:41.848+00:00",
  },
  {
    _id: "6415b0d1aef39ae82c93389f",
    userId: "6415a045d7154777b2bc3121",
    userPicturePath:
      "https://tse3.mm.bing.net/th/id/OIP.zJi0FdQ-QylqsgB5SvticgHaLH?pid=ImgDet&w=199&h=298&c=7&dpr=1.3",
    userName: "abel",
    ventMood: "tried",
    ventText:
      "I dumped my bf because he is ugly - There's this guy who loved me to death, I was his first. I slept with him and we did many things. He tells me that he would do anything for me. But the thing is, He is ugly. I tell Him he looks good to not hurt his feelings and he trusted me. The thing is, I don't love him at all. I don't think he looks good neither. Now he is broken, sad, and she's feeling lonely. ",
    tags: ["funny"],
    feelingSame: 2,
    hug: 3,
    smile: 3,
    surprized: 7,
    createdAt: "2023-03-18T12:38:41.848+00:00",
  },
  {
    _id: "6415b0d1aef39ae82c9338a0",
    userId: "6415a045d7154777b2bc3121",
    userPicturePath:
      "https://tse4.mm.bing.net/th/id/OIP.WN1tO7lGJt0LRyoYV_P1AQHaHa?pid=ImgDet&rs=1",
    userName: "abel",
    ventMood: "obssed",
    ventText:
      "Okay so i don't know why I am writing this but am feeling so sad no one to talk to( even if I want to I don't want to for some reasons) no one listens no one cares not that anybody cares. Just learn to standalone when u r sad the ugliest timing for me tho for this",
    tags: ["cool"],
    feelingSame: 2,
    hug: 3,
    smile: 3,
    surprized: 7,
    createdAt: "2023-03-18T12:38:41.848+00:00",
  },
  {
    _id: "6415b0d1aef39ae82c9338a1",
    userId: "6415a045d7154777b2bc3121",
    userPicturePath:
      "https://tse1.mm.bing.net/th/id/OIP.mHW53jey0964kxQqcgCj9gHaLH?pid=ImgDet&w=199&h=298&c=7&dpr=1.3",
    userName: "abel",
    ventMood: "dead",
    ventText: "i am dead buddy",
    tags: ["dead"],
    feelingSame: 2,
    hug: 3,
    smile: 3,
    surprized: 7,
    createdAt: "2023-03-18T12:38:41.848+00:00",
  },
  {
    _id: "6415b0d1aef39ae82c9338a2",
    userId: "6415aa9a67eb7fe5042d4e9c",
    userPicturePath:
      "https://th.bing.com/th/id/R.f71a5d8b2f00a131d91be1992f4148ce?rik=1s1GZd2yhA7ICA&riu=http%3a%2f%2fex1.co.uk%2fex1%2fwp-content%2fuploads%2f2017%2f01%2fHeadshot-Portrait-Photographer-20170119-_NIK1651-E-E.jpg&ehk=kVHAKoM3gvKz7vyjd8IrUCqxHX9nLRqfoPrIhCmd9CM%3d&risl=&pid=ImgRaw&r=0",
    userName: "eden",
    ventMood: "tired",
    ventText:
      "Have you ever thought of unblocking your ex after years has passed? And if u unblock them what consiquences will it bring? If they saw u unblocked them and messaged u would u respond or just leave it as it is? I am asking this because I have been contemplating to unblocking her this past week's?",
    tags: ["afraied"],
    feelingSame: 2,
    hug: 3,
    smile: 3,
    surprized: 7,
    createdAt: "2023-03-18T12:38:41.848+00:00",
  },
  {
    _id: "6415b0d1aef39ae82c93389e",
    userId: "6415aa9a67eb7fe5042d4e9c",
    userPicturePath:
      "https://4.bp.blogspot.com/-MP21WQ5JmyI/U1-EXkDB95I/AAAAAAAAAQE/LKITj1GPmgg/s1600/Dylan+W+Barnes-1+resized.jpg",
    userName: "eden",
    ventMood: "tired",
    ventText:
      "I just hate it here. I constantly find myself bullshitting. Everything I touch, ✨ruined✨. I couldn’t be good enough for myself, my boyfriend, my mom. I couldn’t even treat him right cuz of my fucking mental instability and stupidity. And he doesn’t wanna let this relationship go even if I wanted to set him free. He chooses to stick by me no matter the fuck happens. I couldn’t handle his patience and care for me. I’m in a loop of trying to be a better person but noooo…what even holds me back? I just being selfish. Ugh this hurts man. I wanna unalive myself sometimes.",
    tags: ["afraied"],
    feelingSame: 2,
    hug: 3,
    smile: 3,
    surprized: 7,
    createdAt: "2023-03-18T12:38:41.848+00:00",
  },
];
const emotions = [
  { text: "happy", emoji: "😃" },
  { text: "sad", emoji: "😃" },
  { text: "smile", emoji: "😃" },
  { text: "funny", emoji: "😃" },
  { text: "afraid", emoji: "😃" },
  { text: "crying", emoji: "😃" },
  { text: "loved", emoji: "😃" },
  { text: "jolly", emoji: "😃" },
  { text: "curious", emoji: "😃" },
  { text: "lonely", emoji: "😃" },
  { text: "concerned", emoji: "😃" },
  { text: "good", emoji: "😃" },
  { text: "goofy", emoji: "😃" },
  { text: "calm", emoji: "😃" },
  { text: "missing", emoji: "😃" },
  { text: "pumped", emoji: "😃" },
  { text: "bad", emoji: "😃" },
  { text: "super", emoji: "😃" },
  { text: "down", emoji: "😃" },
  { text: "satisfied", emoji: "😃" },
];

export { vent, emotions };
